In [1]:
import pandas as pd
import numpy as np

#read in 2018 CLUMPS results
clumps_results = pd.read_csv('CLUMPS_2018_results.txt',sep='\t')
#Select results with P< 0.5
#clumps_results = clumps_results.loc[clumps_results['CLUMPS_P']]

uniprot_file = '/mnt/nfs/rodisks/canine-dfc227bb1d32318e38039093e567f2bd/uniprot_map/huniprot2pdb.run18.filt.txt'
uniprotmap = pd.read_csv(uniprot_file,
                        names=['u1', #uniprot id
                         'u2', #also uniprot iD (should be the same for AF, )
                         'struct', #name of structure/chain - 1 chain per peptide in AF?
                         'blat', #- not relevant for AF
                         'AA:AA list' #colon separated amino acid positions - should be 1:1, 2:2 etc. for AF? - revisit this
                        ],
                        sep='\t')

In [2]:
uniprotmap

,u1,u2,struct,blat,AA:AA list
0,P55008,P55008,2d58-A,-,17:17 18:18 19:19 20:20 21:21 22:22 23:23 24:2...
1,P55008,P55008,2g2b-A,-,2:5 3:6 4:7 5:8 6:9 7:10 8:11 9:12 10:13 11:14...
2,A0A0B4J1V1,P01764,4kfz-D,uhit_identity:86.32 evalue:2e-71 pdb_identity:...,16:-3 17:-2 18:-1 19:0 20:1 21:2 22:3 23:4 24:...
3,Q8NGK1,P02699,4x1h-A,uhit_identity:21.5 evalue:0.0002 pdb_identity:...,34:42 35:43 36:44 37:45 38:46 39:47 40:48 41:4...
4,Q99218,C9E3B4,3ipk-B,uhit_identity:25 evalue:9e-05 pdb_identity:22.22,86:866 87:867 88:868 89:869 90:870 91:871 92:8...
...,...,...,...,...,...
102899,P84243,-,2puy-E,evalue:-5.20458 pdb_identity:100,2:1 3:2 4:3 5:4 6:5 7:6 8:7 9:8 10:9 11:10
102900,P28288,-,3kpl-C,evalue:-1.3917 pdb_identity:100,164:1 165:2 166:3 167:4 168:5 169:6 170:7 171:...
102901,P79483,-,6ati-B,evalue:-5.24995e-129 pdb_identity:90,31:2 32:3 33:4 34:5 35:6 36:7 37:8 38:9 39:10 ...
102902,P01911,-,6ati-B,evalue:-6.7549e-129 pdb_identity:90.53,31:2 32:3 33:4 34:5 35:6 36:7 37:8 38:9 39:10 ...
102903,P01008,-,1br8-P,evalue:-0.457284 pdb_identity:100,412:1 413:2 414:3 415:4 416:5 417:6 418:7 419:...

In [3]:
clumps_results

,GENE_NAMES,UNIPROT_ID,IN_CANCER_GENE_LISTS,MAPPED_UNIPROT_ID,PDBID-CHAIN,PDB_FRAGMENT,UNIPROT_SEQ_LENGTH,MAP_START,MAP_END,PERCENT_IDENTITY,NSITES,NSAMPLES,CLUMPS_P,CLUMPS_Q_FULL,CLUMPS_Q_RESTRICTED,NOTES
0,ATM,Q13315,"C,S,M",Q13315,5np1-A,NaN,3056.0,3,3056,100.0,388,403,0.0,0.0,0.0,exact p-value will be calculated (but will be ...
1,BRAF,P15056,"C,S,M",P15056,3d4q-B,NaN,766.0,448,723,100.0,61,801,0.0,0.0,0.0,exact p-value will be calculated (but will be ...
2,MTOR,P42345,"C,S,M",P42345,5h64-A,NaN,2549.0,210,2549,100.0,300,367,0.0,0.0,0.0,exact p-value will be calculated (but will be ...
3,PIK3CA,P42336,"C,S,M",P42336,5fi4-A,NaN,1068.0,2,1062,100.0,211,1625,0.0,0.0,0.0,exact p-value will be calculated (but will be ...
4,PPP2R1A,P30153,"C,S,M",P30153,1b3u-B,NaN,589.0,2,589,100.0,122,218,0.0,0.0,0.0,exact p-value will be calculated (but will be ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20312,TSPAN19,P0C672,NaN,Q8ITD7,2m7z-A,NaN,248.0,110,211,20.6,11,12,1.0,1.0,-1.0,NaN
20313,TTN,Q8WZ42,NaN,Q64487,4yh7-A,NaN,34350.0,26691,27202,22.8,101,112,1.0,1.0,-1.0,NaN
20314,VWDE,Q8N2E2,NaN,Q9Y5W5,2ygq-A,NaN,1590.0,1076,1326,20.9,14,16,1.0,1.0,-1.0,NaN
20315,ZNF772,Q68DY9,NaN,P03001,1tf6-D,NaN,489.0,138,346,25.2,25,25,1.0,1.0,-1.0,NaN
20316,ZNF835,Q9Y2P0,NaN,D9IWL3,5v3g-A,NaN,537.0,303,469,55.1,50,74,1.0,1.0,-1.0,NaN

In [4]:
mc3maf = pd.read_csv('MC3-14k-merge_v1.variant_classification.maf',sep='\t')
mc3maf

,Chromosome,Start_position,Reference_Allele,Tumor_Seq_Allele2,Hugo_Symbol,Tumor_Sample_Barcode,Variant_Type,ttype,is_coding,Variant_Classification,patient
0,1,10417,C,G,NaN,BDD-FUC_307,SNP,BRCA,0,IGR,BDD-FUC_307
1,1,13421,A,T,NaN,PB0133,SNP,MISC,0,RNA,PB0133
2,1,17482,C,T,NaN,TCGA-58-8390,SNP,LUSC,0,IGR,TCGA-58-8390
3,1,69486,C,T,OR4F5,DLBCL-Ls2848,SNP,DLBC,1,Silent,DLBCL-Ls2848
4,1,69516,G,A,OR4F5,TCGA-17-Z056,SNP,LUAD,1,Nonsense,TCGA-17-Z056
...,...,...,...,...,...,...,...,...,...,...,...
4082141,24,24457560,G,A,NaN,TCGA-BR-8680-01A-11D-2394-08,SNP,STAD,0,Intron,TCGA-BR-8680-01A-11D-2394-08
4082142,24,24460678,G,T,NaN,TCGA-LN-A49L-01A-11D-A247-09,SNP,ESCA,0,Intron,TCGA-LN-A49L-01A-11D-A247-09
4082143,24,24460745,G,A,NaN,TCGA-FW-A3R5-06A-11D-A23B-08,SNP,SKCM,0,Intron,TCGA-FW-A3R5-06A-11D-A23B-08
4082144,24,24460817,G,A,NaN,TCGA-66-2783-01A-01D-1267-08,SNP,LUSC,0,Intron,TCGA-66-2783-01A-01D-1267-08
4082145,24,24460819,T,A,NaN,TCGA-66-2744-01A-01D-0983-08,SNP,LUSC,0,Intron,TCGA-66-2744-01A-01D-0983-08

In [5]:
uniprotmap

,u1,u2,struct,blat,AA:AA list
0,P55008,P55008,2d58-A,-,17:17 18:18 19:19 20:20 21:21 22:22 23:23 24:2...
1,P55008,P55008,2g2b-A,-,2:5 3:6 4:7 5:8 6:9 7:10 8:11 9:12 10:13 11:14...
2,A0A0B4J1V1,P01764,4kfz-D,uhit_identity:86.32 evalue:2e-71 pdb_identity:...,16:-3 17:-2 18:-1 19:0 20:1 21:2 22:3 23:4 24:...
3,Q8NGK1,P02699,4x1h-A,uhit_identity:21.5 evalue:0.0002 pdb_identity:...,34:42 35:43 36:44 37:45 38:46 39:47 40:48 41:4...
4,Q99218,C9E3B4,3ipk-B,uhit_identity:25 evalue:9e-05 pdb_identity:22.22,86:866 87:867 88:868 89:869 90:870 91:871 92:8...
...,...,...,...,...,...
102899,P84243,-,2puy-E,evalue:-5.20458 pdb_identity:100,2:1 3:2 4:3 5:4 6:5 7:6 8:7 9:8 10:9 11:10
102900,P28288,-,3kpl-C,evalue:-1.3917 pdb_identity:100,164:1 165:2 166:3 167:4 168:5 169:6 170:7 171:...
102901,P79483,-,6ati-B,evalue:-5.24995e-129 pdb_identity:90,31:2 32:3 33:4 34:5 35:6 36:7 37:8 38:9 39:10 ...
102902,P01911,-,6ati-B,evalue:-6.7549e-129 pdb_identity:90.53,31:2 32:3 33:4 34:5 35:6 36:7 37:8 38:9 39:10 ...
102903,P01008,-,1br8-P,evalue:-0.457284 pdb_identity:100,412:1 413:2 414:3 415:4 416:5 417:6 418:7 419:...

In [6]:
uniprotmap = uniprotmap.loc[uniprotmap['struct'].isin(clumps_results['PDBID-CHAIN'])]
uniprotmap = uniprotmap.loc[uniprotmap['u1'].isin(clumps_results['UNIPROT_ID'])]
uniprotmap.reset_index()
uniprotmap

,u1,u2,struct,blat,AA:AA list
1,P55008,P55008,2g2b-A,-,2:5 3:6 4:7 5:8 6:9 7:10 8:11 9:12 10:13 11:14...
2,A0A0B4J1V1,P01764,4kfz-D,uhit_identity:86.32 evalue:2e-71 pdb_identity:...,16:-3 17:-2 18:-1 19:0 20:1 21:2 22:3 23:4 24:...
3,Q8NGK1,P02699,4x1h-A,uhit_identity:21.5 evalue:0.0002 pdb_identity:...,34:42 35:43 36:44 37:45 38:46 39:47 40:48 41:4...
7,Q9Y291,F1S8G3,5aj3-i,uhit_identity:85.85 evalue:2e-60 pdb_identity:...,4:4 5:5 6:6 7:7 8:8 9:9 10:10 11:11 12:12 13:1...
8,Q9H6S3,Q8R5F8,2cy5-A,uhit_identity:40.3 evalue:4e-142 pdb_identity:...,46:30 47:31 48:32 49:33 50:34 51:35 52:36 53:3...
...,...,...,...,...,...
102265,Q92870,O00213,2e45-A,uhit_identity:45.95 evalue:0 pdb_identity:47.62,279:1 280:3 281:4 282:5 283:6 284:7 285:8 286:...
102406,P11362,-,3ojv-C,evalue:-7.71528e-155 pdb_identity:99.53,147:147 148:148 149:149 150:150 151:151 152:15...
102737,P84243,-,5gxq-A,evalue:-1.39586e-66 pdb_identity:96.91,39:38 40:39 41:40 42:41 43:42 44:43 45:44 46:4...
102738,Q6NXT2,-,5gxq-A,evalue:-1.28224e-64 pdb_identity:93.81,38:38 39:39 40:40 41:41 42:42 43:43 44:44 45:4...
102740,P68431,-,5gxq-A,evalue:-1.36994e-63 pdb_identity:92.78,39:38 40:39 41:40 42:41 43:42 44:43 45:44 46:4...

In [7]:
import os

out_dir = 'uniprot_chunks'
chunk_length= 300
if not os.path.exists(out_dir):
    os.mkdir(out_dir)
gl = len(uniprotmap.index)
start = 0
end = chunk_length
i = 0
while end < gl:
    if i < 10:
        num = '0000%s' %i
    elif i < 100:
        num = '000%s' %i
    elif i < 1000:
        num = '00%s' %i
    fn = 'uniprot_chunks/allgenesstructmapped_%s.gz' %num
    uniprotmap.iloc[start:end].to_csv(fn,
            sep='\t',
            header=False,
            index=False)
    i = i + 1
    start = end
    end = end+chunk_length
end = gl

if i < 10:
    num = '0000%s' %i
elif i < 100:
    num = '000%s' %i
elif i < 1000:
    num = '00%s' %i
fn = 'uniprot_chunks/allgenesstructmapped_%s.gz' %num
uniprotmap.iloc[start:end].to_csv(fn,
        sep='\t',
        header=False,
        index=False)