In [1]:
import pandas as pd
import numpy as np

#read in 2018 CLUMPS results
clumps_results = pd.read_csv('CLUMPS_2018_results.txt',sep='\t')
#Select results with P< 0.5
clumps_results = clumps_results.loc[clumps_results['CLUMPS_P']<0.5]

uniprot_file = '/mnt/nfs/ro_disks/canine-c0820e9f17cde673ca995479dc35c9ae/uniprot_map/huniprot2pdb.run18.filt.txt'
uniprotmap = pd.read_csv(uniprot_file,
                        names=['u1', #uniprot id
                         'u2', #also uniprot iD (should be the same for AF, )
                         'struct', #name of structure/chain - 1 chain per peptide in AF?
                         'blat', #- not relevant for AF
                         'AA:AA list' #colon separated amino acid positions - should be 1:1, 2:2 etc. for AF? - revisit this
                        ],
                        sep='\t')

In [2]:
uniprotmap

,u1,u2,struct,blat,AA:AA list
0,P55008,P55008,2d58-A,-,17:17 18:18 19:19 20:20 21:21 22:22 23:23 24:2...
1,P55008,P55008,2g2b-A,-,2:5 3:6 4:7 5:8 6:9 7:10 8:11 9:12 10:13 11:14...
2,A0A0B4J1V1,P01764,4kfz-D,uhit_identity:86.32 evalue:2e-71 pdb_identity:...,16:-3 17:-2 18:-1 19:0 20:1 21:2 22:3 23:4 24:...
3,Q8NGK1,P02699,4x1h-A,uhit_identity:21.5 evalue:0.0002 pdb_identity:...,34:42 35:43 36:44 37:45 38:46 39:47 40:48 41:4...
4,Q99218,C9E3B4,3ipk-B,uhit_identity:25 evalue:9e-05 pdb_identity:22.22,86:866 87:867 88:868 89:869 90:870 91:871 92:8...
...,...,...,...,...,...
102899,P84243,-,2puy-E,evalue:-5.20458 pdb_identity:100,2:1 3:2 4:3 5:4 6:5 7:6 8:7 9:8 10:9 11:10
102900,P28288,-,3kpl-C,evalue:-1.3917 pdb_identity:100,164:1 165:2 166:3 167:4 168:5 169:6 170:7 171:...
102901,P79483,-,6ati-B,evalue:-5.24995e-129 pdb_identity:90,31:2 32:3 33:4 34:5 35:6 36:7 37:8 38:9 39:10 ...
102902,P01911,-,6ati-B,evalue:-6.7549e-129 pdb_identity:90.53,31:2 32:3 33:4 34:5 35:6 36:7 37:8 38:9 39:10 ...
102903,P01008,-,1br8-P,evalue:-0.457284 pdb_identity:100,412:1 413:2 414:3 415:4 416:5 417:6 418:7 419:...

In [3]:
clumps_results

,GENE_NAMES,UNIPROT_ID,IN_CANCER_GENE_LISTS,MAPPED_UNIPROT_ID,PDBID-CHAIN,PDB_FRAGMENT,UNIPROT_SEQ_LENGTH,MAP_START,MAP_END,PERCENT_IDENTITY,NSITES,NSAMPLES,CLUMPS_P,CLUMPS_Q_FULL,CLUMPS_Q_RESTRICTED,NOTES
0,ATM,Q13315,"C,S,M",Q13315,5np1-A,NaN,3056.0,3,3056,100.0,388,403,0.000,0.000000,0.000000,exact p-value will be calculated (but will be ...
1,BRAF,P15056,"C,S,M",P15056,3d4q-B,NaN,766.0,448,723,100.0,61,801,0.000,0.000000,0.000000,exact p-value will be calculated (but will be ...
2,MTOR,P42345,"C,S,M",P42345,5h64-A,NaN,2549.0,210,2549,100.0,300,367,0.000,0.000000,0.000000,exact p-value will be calculated (but will be ...
3,PIK3CA,P42336,"C,S,M",P42336,5fi4-A,NaN,1068.0,2,1062,100.0,211,1625,0.000,0.000000,0.000000,exact p-value will be calculated (but will be ...
4,PPP2R1A,P30153,"C,S,M",P30153,1b3u-B,NaN,589.0,2,589,100.0,122,218,0.000,0.000000,0.000000,exact p-value will be calculated (but will be ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10919,TRAF3,Q13114,M,Q13114,1rf3-A,NaN,568.0,377,568,100.0,25,27,0.498,0.932705,0.823089,NaN
10923,UPF3B,Q9BZI7,NaN,Q9BZI7,1uw4-A,NaN,483.0,50,140,100.0,14,17,0.499,0.932705,-1.000000,NaN
10926,ZNF142,P52746,NaN,P49711,5t0u-A,NaN,1687.0,1133,1353,25.8,19,21,0.498,0.932705,-1.000000,NaN
10927,ZNF142,P52746,NaN,D9IWL3,5v3g-A,NaN,1687.0,1449,1616,38.7,26,34,0.499,0.932705,-1.000000,NaN
10934,ZNF790,Q6PG37,NaN,Q07230,2i13-A,NaN,636.0,207,360,57.1,24,30,0.498,0.932705,-1.000000,NaN

In [4]:
mc3maf = pd.read_csv('MC3-14k-merge_v1.variant_classification.maf',sep='\t')
mc3maf

,Chromosome,Start_position,Reference_Allele,Tumor_Seq_Allele2,Hugo_Symbol,Tumor_Sample_Barcode,Variant_Type,ttype,is_coding,Variant_Classification,patient
0,1,10417,C,G,NaN,BDD-FUC_307,SNP,BRCA,0,IGR,BDD-FUC_307
1,1,13421,A,T,NaN,PB0133,SNP,MISC,0,RNA,PB0133
2,1,17482,C,T,NaN,TCGA-58-8390,SNP,LUSC,0,IGR,TCGA-58-8390
3,1,69486,C,T,OR4F5,DLBCL-Ls2848,SNP,DLBC,1,Silent,DLBCL-Ls2848
4,1,69516,G,A,OR4F5,TCGA-17-Z056,SNP,LUAD,1,Nonsense,TCGA-17-Z056
...,...,...,...,...,...,...,...,...,...,...,...
4082141,24,24457560,G,A,NaN,TCGA-BR-8680-01A-11D-2394-08,SNP,STAD,0,Intron,TCGA-BR-8680-01A-11D-2394-08
4082142,24,24460678,G,T,NaN,TCGA-LN-A49L-01A-11D-A247-09,SNP,ESCA,0,Intron,TCGA-LN-A49L-01A-11D-A247-09
4082143,24,24460745,G,A,NaN,TCGA-FW-A3R5-06A-11D-A23B-08,SNP,SKCM,0,Intron,TCGA-FW-A3R5-06A-11D-A23B-08
4082144,24,24460817,G,A,NaN,TCGA-66-2783-01A-01D-1267-08,SNP,LUSC,0,Intron,TCGA-66-2783-01A-01D-1267-08
4082145,24,24460819,T,A,NaN,TCGA-66-2744-01A-01D-0983-08,SNP,LUSC,0,Intron,TCGA-66-2744-01A-01D-0983-08

In [5]:
#select genes of interest

#previously identified genes
goi = [
    'ATM',
    'RHOA',
    'CNOT9',
    'RQCD1',
    'DDX3X',
    'MTOR'
    ]

#random genes
np.random.seed(1234)

#remove zinc fingers - add a lot of redundant structures to permute over
clumps_results = clumps_results.loc[clumps_results['GENE_NAMES'].notna()]
clumps_results = clumps_results.loc[~clumps_results['GENE_NAMES'].str.contains('ZNF')]
clumps_results

,GENE_NAMES,UNIPROT_ID,IN_CANCER_GENE_LISTS,MAPPED_UNIPROT_ID,PDBID-CHAIN,PDB_FRAGMENT,UNIPROT_SEQ_LENGTH,MAP_START,MAP_END,PERCENT_IDENTITY,NSITES,NSAMPLES,CLUMPS_P,CLUMPS_Q_FULL,CLUMPS_Q_RESTRICTED,NOTES
0,ATM,Q13315,"C,S,M",Q13315,5np1-A,NaN,3056.0,3,3056,100.0,388,403,0.000,0.000000,0.000000,exact p-value will be calculated (but will be ...
1,BRAF,P15056,"C,S,M",P15056,3d4q-B,NaN,766.0,448,723,100.0,61,801,0.000,0.000000,0.000000,exact p-value will be calculated (but will be ...
2,MTOR,P42345,"C,S,M",P42345,5h64-A,NaN,2549.0,210,2549,100.0,300,367,0.000,0.000000,0.000000,exact p-value will be calculated (but will be ...
3,PIK3CA,P42336,"C,S,M",P42336,5fi4-A,NaN,1068.0,2,1062,100.0,211,1625,0.000,0.000000,0.000000,exact p-value will be calculated (but will be ...
4,PPP2R1A,P30153,"C,S,M",P30153,1b3u-B,NaN,589.0,2,589,100.0,122,218,0.000,0.000000,0.000000,exact p-value will be calculated (but will be ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10915,SSPO,A2VEC9,NaN,P27918,1w0s-A,NaN,5150.0,3184,3533,29.5,37,48,0.498,0.932705,-1.000000,NaN
10916,SYT11,Q9BT88,NaN,Q62747,6ank-A,NaN,431.0,157,428,44.9,50,52,0.498,0.932705,-1.000000,NaN
10918,TOR1AIP2,Q8NFQ8,NaN,Q8NFQ8,5j1t-B,NaN,470.0,236,470,100.0,37,43,0.499,0.932705,-1.000000,NaN
10919,TRAF3,Q13114,M,Q13114,1rf3-A,NaN,568.0,377,568,100.0,25,27,0.498,0.932705,0.823089,NaN
10923,UPF3B,Q9BZI7,NaN,Q9BZI7,1uw4-A,NaN,483.0,50,140,100.0,14,17,0.499,0.932705,-1.000000,NaN

In [6]:
random_goi = np.random.choice(clumps_results['GENE_NAMES'],50,replace=False)
goi = goi + list(random_goi)
goi

['ATM',
 'RHOA',
 'CNOT9',
 'RQCD1',
 'DDX3X',
 'MTOR',
 'LRGUK',
 'IGKV3-11',
 'KREMEN1',
 'STIP1',
 'WDR53',
 'TRMT6',
 'CRACR2A',
 'ANKRD50',
 'FOXO1',
 'SNX24',
 'OAS3',
 'OR4D9',
 'PTPRJ',
 'HELLS',
 'RBMXL3',
 'SYT6',
 'KCND2',
 'PCDH18',
 'SH3GLB2',
 'UBC',
 'SMC1B',
 'F13A1',
 'ZBTB25',
 'BPI',
 'UBXN11',
 'TRPC4',
 'RBMXL1',
 'FAIM',
 'TNFRSF25',
 'SIGMAR1',
 'FAT2',
 'DDI2',
 'IFNAR1',
 'CDC42BPG',
 'GNMT',
 'IRF3',
 'EEFSEC',
 'KLHL11',
 'FAHD2A',
 'TARBP2',
 'NF2',
 'CEP78',
 'CEBPE',
 'SCN2A',
 'TRIM25',
 'ST6GALNAC3',
 'SH3RF3',
 'NLRC5',
 'ASPHD1',
 'KIF18A']

In [7]:
mc3maf = mc3maf.loc[mc3maf['Hugo_Symbol'].isin(goi)]
mc3maf

,Chromosome,Start_position,Reference_Allele,Tumor_Seq_Allele2,Hugo_Symbol,Tumor_Sample_Barcode,Variant_Type,ttype,is_coding,Variant_Classification,patient
2870,1,6521497,C,T,TNFRSF25,DO10806,SNP,PRAD,1,Silent,DO10806
2871,1,6521698,G,A,TNFRSF25,PB-PB0079,SNP,MISC,1,Silent,PB-PB0079
2872,1,6522143,T,C,TNFRSF25,LC_S31,SNP,LUAD,1,Missense,LC_S31
2873,1,6522195,G,C,TNFRSF25,GC3_T,SNP,STAD,1,Missense,GC3_T
2874,1,6522198,G,A,TNFRSF25,TCGA-BR-4190,SNP,STAD,1,Missense,TCGA-BR-4190
...,...,...,...,...,...,...,...,...,...,...,...
4038150,23,114427079,C,T,RBMXL3,TCGA-EA-A3Y4-01A-51D-A243-09,SNP,CESC,1,Silent,TCGA-EA-A3Y4-01A-51D-A243-09
4038151,23,114427079,C,A,RBMXL3,TCGA-EO-A22U-01A-11D-A17W-09,SNP,UCEC,1,Silent,TCGA-EO-A22U-01A-11D-A17W-09
4038152,23,114427102,G,A,RBMXL3,TCGA-E6-A1LX-01A-11D-A14G-09,SNP,UCEC,1,Missense,TCGA-E6-A1LX-01A-11D-A14G-09
4038153,23,114427153,G,A,RBMXL3,TCGA-BG-A222-01A-11D-A159-09,SNP,UCEC,1,Missense,TCGA-BG-A222-01A-11D-A159-09
4038154,23,114427160,C,T,RBMXL3,TCGA-AP-A1DV-01A-21D-A135-09,SNP,UCEC,1,Silent,TCGA-AP-A1DV-01A-21D-A135-09

In [8]:
clumps_results = clumps_results.loc[clumps_results['GENE_NAMES'].isin(goi)]
clumps_results

,GENE_NAMES,UNIPROT_ID,IN_CANCER_GENE_LISTS,MAPPED_UNIPROT_ID,PDBID-CHAIN,PDB_FRAGMENT,UNIPROT_SEQ_LENGTH,MAP_START,MAP_END,PERCENT_IDENTITY,NSITES,NSAMPLES,CLUMPS_P,CLUMPS_Q_FULL,CLUMPS_Q_RESTRICTED,NOTES
0,ATM,Q13315,"C,S,M",Q13315,5np1-A,NaN,3056.0,3,3056,100.0,388,403,0.000000,0.000000,0.000000,exact p-value will be calculated (but will be ...
2,MTOR,P42345,"C,S,M",P42345,5h64-A,NaN,2549.0,210,2549,100.0,300,367,0.000000,0.000000,0.000000,exact p-value will be calculated (but will be ...
17,RHOA,P61586,"C,S,M",P61586,6bc0-F,NaN,193.0,3,181,100.0,53,120,0.000002,0.002424,0.000137,NaN
31,CNOT9,Q92600,NaN,Q92600,4cru-B,NaN,299.0,19,285,100.0,38,55,0.000076,0.048221,-1.000000,NaN
57,DDX3X,O00571,"S,M",O00571,4pxa-A,NaN,662.0,135,576,100.0,104,155,0.000389,0.136404,0.012461,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10212,SH3GLB2,Q9NR46,NaN,Q99962,2d4c-B,NaN,395.0,16,291,23.8,25,35,0.465000,0.929704,-1.000000,NaN
10499,CEBPE,Q15744,NaN,P05554,1nwq-C,NaN,281.0,203,262,75.0,14,19,0.485000,0.931116,-1.000000,NaN
10623,STIP1,P31948,NaN,P31948,2lni-A,NaN,543.0,356,477,100.0,18,19,0.482000,0.931116,-1.000000,NaN
10633,TRIM25,Q14258,NaN,Q14258,4ltb-B,NaN,630.0,190,360,100.0,27,30,0.483000,0.931116,-1.000000,NaN
10807,IFNAR1,P17181,NaN,P17181,3se4-A,NaN,557.0,33,329,100.0,33,35,0.496000,0.932128,-1.000000,NaN

In [9]:
uniprotmap = uniprotmap.loc[uniprotmap['struct'].isin(clumps_results['PDBID-CHAIN'])]
uniprotmap = uniprotmap.loc[uniprotmap['u1'].isin(clumps_results['UNIPROT_ID'])]
uniprotmap.reset_index()
uniprotmap

,u1,u2,struct,blat,AA:AA list
437,Q96E39,P38159,2mb0-B,uhit_identity:95.37 evalue:9e-178 pdb_identity...,1:1 2:2 3:3 4:4 5:5 6:6 7:7 8:8 9:9 10:10 11:1...
5938,Q9Y343,Q9Y343,4az9-B,-,1:1 2:2 3:3 4:4 5:5 6:6 7:7 8:8 9:9 10:10 11:1...
7108,Q13315,Q13315,5np1-A,-,3:3 4:4 5:5 6:6 7:7 8:8 9:9 10:10 11:11 12:12 ...
7117,Q9NZV8,Q63881,1s6c-B,uhit_identity:99.05 evalue:0 pdb_identity:100,1:217 2:218 3:219 4:220 5:221 6:222 7:223 8:22...
7119,Q9NZV8,P63142,3lut-B,uhit_identity:33.4 evalue:1e-82 pdb_identity:3...,43:35 44:36 45:37 46:38 47:39 48:40 49:41 50:4...
...,...,...,...,...,...
94252,P31948,P31948,2lni-A,-,356:12 357:13 358:14 359:15 360:16 361:17 362:...
94253,P31948,P31948,1elr-A,-,223:223 224:224 225:225 226:226 227:227 228:22...
95643,P00488,P00488,1fie-B,-,11:10 12:11 13:12 14:13 15:14 16:15 17:16 18:1...
100133,Q8NI77,Q8NI77,5ocu-K,-,10:10 11:11 12:12 13:13 14:14 15:15 16:16 17:1...
101534,Q5U4P2,Q12797,5apa-A,uhit_identity:37.78 evalue:2e-19 pdb_identity:...,251:627 252:628 253:629 254:630 255:631 256:63...

In [10]:
import os

out_dir = 'uniprot_chunks'
chunk_length= 10
if not os.path.exists(out_dir):
    os.mkdir(out_dir)
gl = len(uniprotmap.index)
start = 0
end = chunk_length
i = 0
while end < gl:
    if i < 10:
        num = '0000%s' %i
    elif i < 100:
        num = '000%s' %i
    elif i < 1000:
        num = '00%s' %i
    fn = 'uniprot_chunks/uniprot50genes_%s.gz' %num
    uniprotmap.iloc[start:end].to_csv(fn,
            sep='\t',
            header=False,
            index=False)
    i = i + 1
    start = end
    end = end+chunk_length
end = gl

if i < 10:
    num = '0000%s' %i
elif i < 100:
    num = '000%s' %i
elif i < 1000:
    num = '00%s' %i
fn = 'uniprot_chunks/uniprot50genes_%s.gz' %num
uniprotmap.iloc[start:end].to_csv(fn,
        sep='\t',
        header=False,
        index=False)

In [11]:
mc3maf.to_csv('MC3-14k-merge_v1.50_genes.variant_classification.maf',sep='\t',index=False)